### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-ft-affiliate-ribbon bundle size difference from 4.0.0 to 0ff686c63f152059732d7b10e0d91a23e11fe4db
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-ft-affiliate-ribbon bundle size difference from 4.0.0 to ba826081c6922f3737b40e14fb9ed3bce7ab79de
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-ft-affiliate-ribbon bundle size difference from 4.0.0 to 1fc95caf89207c0ffc496276cddfecb60ec7bde9
No significant bundle size differences found.

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
o-ft-affiliate-ribbon bundle size difference from 4.0.0 to 3bc181061f6cb1d1aacc08a285778d16bb2b8e51
No significant bundle size differences found.

**Pull request merged**
