### PR TITLE
Breaking

### PR DESCRIPTION
**Pull request by notlee**
See https://github.com/Financial-Times/o-ft-affiliate-ribbon/issues/24

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-ft-affiliate-ribbon bundle size difference from 3.1.1 to f5e19eaa1cb8b7daf2868d0b9e914cd8b0757e09
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-ft-affiliate-ribbon bundle size difference from 3.1.1 to c295e7c8c8e426383163d7b7e887a6c93e42818d
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-ft-affiliate-ribbon bundle size difference from 3.1.1 to cdc7deadfe41183d0c02ec2c0d84e88df39946c7
No significant bundle size differences found.

**Review by rowanmanning — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
o-ft-affiliate-ribbon bundle size difference from 3.1.1 to d01674abfc327e66fb2eb3c5c7e38f7acc138287
No bundle size differences found.

**Pull request merged**
